# Generated by Django 5.2.3 on 2025-07-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='decommission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('DESKTOP', 'Desktop'), ('PRINTER', 'Printer'), ('SERVER', 'Server'), ('STORAGE', 'Storage Device'), ('NETWORK', 'Network Device'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'In Use'), ('IN_STOCK', 'In Stock'), ('UNDER_REPAIR', 'Under Repair'), ('RETIRED', 'Retired'), ('DECOMMISSIONED', 'Decommissioned')], default='IN_STOCK', max_length=20),
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PURCHASED', 'Purchased'), ('INSTALLED', 'Installed'), ('REPAIRED', 'Repaired'), ('MAINTAINED', 'Maintained'), ('REPLACED', 'Replaced'), ('RETIRED', 'Retired'), ('DECOMMISSIONED', 'Decommissioned')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('issue_description', models.TextField()),
                ('repair_description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_records', to='inventory.equipment')),
            ],
        ),
    ]
