# Generated by Django 5.2.4 on 2025-07-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment_asset_tag_equipment_decommission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('HEADSET', 'Headset'), ('PHONE', 'Phone'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('DESKTOP', 'Desktop'), ('PRINTER', 'Printer'), ('SERVER', 'Server'), ('STORAGE', 'Storage Device'), ('NETWORK', 'Network Device'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
