# Generated by Django 5.2.3 on 2025-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in USD', max_digits=10, null=True),
        ),
    ]
