# Generated by Django 5.2.4 on 2025-07-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_equipment_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_price',
        ),
    ]
